apiVersion: v1
kind: PersistentVolume
metadata:
    name: deluge-downloads
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        server: saturn.sol.milkyway
        path: /SaturnPool/Downloads/
    storageClassName: nfs
