apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: deluge-downloads
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 10Ti
    storageClassName: nfs
    volumeName: deluge-downloads
