apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: deluge-config
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
    storageClassName: nfs
    volumeName: deluge-config
