apiVersion: v1
kind: Service
metadata:
    name: deluge
    annotations:
    labels:
        app: deluge
spec:
    type: LoadBalancer
    selector:
        app: deluge
    ports:
    - name: "http-deluge-web"
      protocol: TCP
      targetPort: 8112
      port: 8112

