apiVersion: v1
kind: PersistentVolume
metadata:
    name: tautulli-plex
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Plex/config/Library/Application Support/Plex Media Server/Logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: tautulli-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Tautulli
