---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deleting the Personal Website manifests from Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
            state: absent            
        with_items:
            - "svc.yml.j2"
            - "dep.yml.j2"
            - "cm_analyticsjs.yml.j2"
            - "cm_weatherrc.yml.j2"      
            - "pvc.yml.j2"  
            - "pv_files.yml.j2"                  
