---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Creating a PVC for the Data Files.
        k8s:
            definition: "{{ lookup('template', './manifests/pvc.yml.j2') | from_yaml }}"

      - name: Creating a PV for the Data Files.
        k8s:
            definition: "{{ lookup('template', './manifests/pv_files.yml.j2') | from_yaml }}"

      - name: Creating a CM for the Google Analytics tracking ID.
        k8s:
            definition: "{{ lookup('template', './manifests/cm_analyticsjs.yml.j2') | from_yaml }}"

      - name: Creating a CM for the weatherpy config file.
        k8s: 
            definition: "{{ lookup('template', './manifests/cm_weatherrc.yml.j2') | from_yaml }}"

      - name: Creating a Service for the deployment.
        k8s:
            definition: "{{ lookup('template', './manifests/service.yml.j2') | from_yaml }}"

      - name: Creating an Ingress for the deployment.
        k8s:
            definition: "{{ lookup('template', './manifests/ingress.yml.j2') | from_yaml }}"            

      - name: Creating a Deployment.
        k8s: 
            definition: "{{ lookup('template', './manifests/deployment.yml.j2') | from_yaml }}"

      - name: Waiting for the deployment to be ready.
        wait_for:
            host: "{{ website_hostname }}"
            port: 80
            timeout: 300
            msg: "Website not available after 5 minutes. Something has probably gone wrong."
