---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deploying the Personal Website manifests to Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
        with_items:
            - "pv_files.yml.j2"          
            - "pvc.yml.j2"
            - "cm_analyticsjs.yml.j2"
            - "cm_weatherrc.yml.j2"
            - "svc.yml.j2"
            - "dep.yml.j2"

      - name: Waiting for the deployment to be ready.
        wait_for:
            host: "{{ website_hostname }}"
            port: 80
            timeout: 300
            msg: "Website not available after 5 minutes. Something has probably gone wrong."
