apiVersion: v1
kind: PersistentVolume
metadata:
    name: confluence-data
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Confluence/data
