apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: confluence-data
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 10Gi
    volumeName: confluence-data
