apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: confluence-postgres-data
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 100Gi
    volumeName: confluence-postgres-data
