---
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ./vars.yml

      - name: Deleting the Unifi Controller manifests from Kubernetes.
        k8s:
            definition: "{{ lookup('template', './manifests/{{ item }}') | from_yaml }}"
            state: absent            
        with_items:
            - "cm_unifi_controller_mongodb_config.yml.j2"
            - "cm_unifi_controller_system_properties.yml.j2"  
            - "sec_unifi_controller_mongodb_password.yml.j2"          
            - "pv_unifi_controller_backups.yml.j2"           
            - "pv_unifi_controller_data.yml.j2"
            - "pv_unifi_controller_mongodb.yml.j2"
            - "pvc_unifi_controller_backups.yml.j2"                       
            - "pvc_unifi_controller_data.yml.j2"
            - "pvc_unifi_controller_mongodb.yml.j2"
            - "dep_unifi_controller.yml.j2"
            - "dep_unifi_controller_mongodb.yml.j2"
            - "svc_unifi_controller_mongodb.yml.j2"
            - "svc_unifi_controller_tcp.yml.j2"
            - "svc_unifi_controller_udp.yml.j2" 
