apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-anime
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        server: saturn.sol.milkyway
        path: /SaturnPool/Anime
    storageClassName: nfs
