apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    nfs:
        server: saturn.sol.milkyway
        path: /SaturnPool/Kubernetes/Plex/config
    storageClassName: nfs
