apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-movies
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        server: saturn.sol.milkyway
        path: /SaturnPool/Movies
    storageClassName: nfs
