apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-tv-shows
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    nfs:
        server: saturn.sol.milkyway
        path: /SaturnPool/TV Shows
    storageClassName: nfs
