apiVersion: v1
kind: PersistentVolume
metadata:
    name: deluge-config
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Deluge
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: deluge-downloads
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Downloads/
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: deluge-fileserver
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/
