apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonarr-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Sonarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonarr-tv-shows
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/TV Shows
