apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-anime
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Anime
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-audiobooks
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Audiobooks
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Kubernetes/Plex/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-movies
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-music
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Music
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-tv-shows
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/TV Shows
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: plex-unsorted
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /SaturnPool/Unsorted
